# Generated by Django 2.0 on 2019-03-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(default=None, max_length=30)),
                ('date_loaded', models.DateField()),
                ('date_off_loaded', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('pic_slip_number', models.IntegerField()),
                ('products', models.CharField(max_length=3)),
                ('expected_quantity_to_deliver', models.IntegerField()),
                ('recieved_quantity', models.IntegerField()),
                ('shortage', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'deliverie',
            },
        ),
        migrations.CreateModel(
            name='LoadingDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=3)),
                ('loading_average', models.IntegerField(null=True)),
                ('expect_quantity', models.IntegerField()),
                ('loaded_quantity', models.IntegerField(null=True)),
                ('remaining_quantity', models.IntegerField(null=True)),
                ('total_trucks', models.IntegerField(null=True)),
                ('loaded_trucks', models.IntegerField(null=True)),
                ('remaining_trucks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=30)),
                ('depot', models.CharField(max_length=10)),
                ('volume', models.CharField(blank=True, max_length=30)),
                ('volume_delivered', models.CharField(blank=True, max_length=30)),
                ('order_status', models.CharField(blank=True, max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('loaded_date', models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=20)),
                ('insurance', models.CharField(max_length=20)),
                ('gps_tracking', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(default=None, max_length=30)),
                ('driver_id_number', models.CharField(default=None, max_length=30)),
                ('driver_phone_number', models.CharField(default=None, max_length=30)),
                ('driving_license', models.CharField(max_length=20)),
                ('good_conduct', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relation_truck', to='wayshiree.Truck'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='truck',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relation_delivery', to='wayshiree.Truck'),
        ),
    ]
